// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5ycy72lQ-YLa9HuzYtkDMki3c7LAduxU',
    appId: '1:932502143466:web:c4ce5879ce8fc982dfb293',
    messagingSenderId: '932502143466',
    projectId: 'component5c',
    authDomain: 'component5c.firebaseapp.com',
    storageBucket: 'component5c.appspot.com',
    measurementId: 'G-LRD0ZS0CZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4_Dt4gyzea6Jty9wFLOazhfGZKApy0u8',
    appId: '1:932502143466:android:ea244587d76b02a2dfb293',
    messagingSenderId: '932502143466',
    projectId: 'component5c',
    storageBucket: 'component5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZO1hQeEqBzRLhMz5DzRsbPhkI4vIJtb0',
    appId: '1:932502143466:ios:89e32cf9979a52d7dfb293',
    messagingSenderId: '932502143466',
    projectId: 'component5c',
    storageBucket: 'component5c.appspot.com',
    iosBundleId: 'com.example.practica3',
  );
}
