import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return  Scaffold(
      appBar:  AppBar(
        title: const Text('Componentes de flutter'),
      ),
        body: ListView(
          children: const[
            Text('Pumas campeones de la Ligamx'),
            Text('Pumas campeones de la concacaf'),
            Text('Pumas campeones de la champions'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),
            Text('Pumas campeones de la premier'),

            
          ],
        ),
      );
  }
}